version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm packages"
          paths: 
           - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys: "npm packages"
      - run: npm run test
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys: "npm packages"
      - run: npm run audit

workflows:
  create_ci_pipeline:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires: 
            - test